modLoader = "javafml"
loaderVersion = "${fmlVersionRange}"

license = "MIT"
issueTrackerURL = "https://github.com/realleoxian/MoonlightCore/issues"
showAsResourcePack = false

[[mods]]
    modId = "moonlightcore"
    version = "${version}"
    displayName = "Moonlight Core"
    credits = "Leoxian"
    authors = "Leoxian"
    description = "MoonlightCore is a layer abstraction that simplifies the process of creating multi-loader mods by prividing loader-agnostic APIs"

    [[dependencies.moonlightcore]]
        modId = "forge"
        mandatory = true
        versionRange = "${forgeVersionRange}"
        ordering = "NONE"
        side = "BOTH"