modLoader = "javafml"
loaderVersion = "${fmlVersionRange}"

license = "MIT"
issueTrackerURL = "${githubUrl}/issues"
showAsResourcePack = false

[[mods]]
    modId = "moonlightcore"
    version = "${modVersion}"
    displayName = "MoonlightCore"
    credits = "RealLeoxian"
    authors = "RealLeoxian"
    displayURL = "${githubUrl}"
    description = "MoonlightCore its a layer abstraction (actually it isn't (kinda?)) that helps with the multi-loader mod development"

    [[dependencies.moonlightcore]]
        modId = "forge"
        mandatory = true
        versionRange = "${forgeVersionRange}"
        ordering = "NONE"
        side = "BOTH"