plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neoformVersionAndTimestamp

    def atFile = file("src/main/resources/META-INF/accesstransformer.cfg")
    if (atFile.exists()) {
        accessTransformers {
            from atFile
            publish atFile
        }
        validateAccessTransformers = true
    }
}

dependencies {
    compileOnly "net.fabricmc:sponge-mixin:0.17.3+mixin.0.8.7"
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.3"))
}

configurations {
    xplatJava {
        canBeResolved = false
        canBeConsumed = true
    }
    xplatResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    xplatJava sourceSets.main.java.sourceDirectories.singleFile
    xplatResources sourceSets.main.resources.sourceDirectories.singleFile
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, 'common')
            }
        }
    }
}