plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev.legacyforge'
}

version = rootProject.version

configurations {
    xplatJava {
        canBeResolved = false
        canBeConsumed = true
    }

    xplatResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

legacyForge {
    mcpVersion = "${mcVersion}"
    validateAccessTransformers = true

    if(file('src/main/resources/META-INF/accesstransformer.cfg')) {
        accessTransformers = ['src/main/resources/META-INF/accesstransformer.cfg']
    }

    parchment {
        minecraftVersion = mcVersion
        mappingsVersion = parchmentVersion
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
}

artifacts {
    xplatJava sourceSets.main.java.sourceDirectories.singleFile
    xplatResources sourceSets.main.resources.sourceDirectories.singleFile
}