plugins {
    id 'moonlightcore-common'
    id 'net.neoforged.moddev.legacyforge'
}

configurations {
    xplatJava {
        canBeResolved = false
        canBeConsumed = true
    }

    xplatResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

dependencies {
    compileOnly("org.spongepowered:mixin:${mixinVersion}")
    compileOnly("io.github.llamalad7:mixinextras-common:${mixinextrasVersion}")
}

legacyForge {
    mcpVersion = "${mcVersion}"

    validateAccessTransformers = true
    accessTransformers.from file("src/main/resources/META-INF/accesstransformer.cfg")

    parchment {
        minecraftVersion = "${mcVersion}"
        mappingsVersion = "${parchmentVersion}"
    }
}

artifacts {
    xplatJava sourceSets.main.java.sourceDirectories.singleFile
    xplatResources sourceSets.main.resources.sourceDirectories.singleFile
}

publishing {
    publications {
        register('xplatJar', MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            url = "file://" + System.getenv("maven_local")
        }
    }
}