plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'de.leoxian.moonlightcore'
version = modVersion

base {
    archivesName = "moonlightcore-${project.name.toLowerCase()}-${mcVersion}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
    withSourcesJar()
    withJavadocJar()
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = 'Sponge'
                url = 'https://repo.spongepowered.org/repository/maven-public/'
            }
        }
        filter {
            includeGroupAndSubgroups('org.spongepowered')
        }
    }

    exclusiveContent {
        forRepositories(
                maven {
                    name = 'ParchmentMC'
                    url = 'https://maven.parchmentmc.org/'
                },
                maven {
                    name = 'NeoForge'
                    url = 'https://maven.neoforged.net/releases'
                }
        )
        filter {
            includeGroup('org.parchmentmc.data')
        }
    }

    mavenCentral()
}

['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations."$variant".outgoing {
        capability("de.leoxian.moonlightcore:${project.name}:$version")
        capability("de.leoxian.moonlightcore:${base.archivesName.get()}:$version")
        capability("de.leoxian.moonlightcore:moonlightcore-${project.name}-${mcVersion}:$version")
        capability("de.leoxian.moonlightcore:moonlightcore:$version")
    }

    publishing.publications.configureEach {
        suppressPomMetadataWarningsFor(variant)
    }
}

sourcesJar {
    from(rootProject.file('LICENSE')) {
        rename { "${it}_MoonlighCore"}
    }

    archiveClassifier = "sources"
}

jar {
    from(rootProject.file('LICENSE')) {
        rename { "${it}_MoonlighCore"}
    }

    manifest {
        attributes([
                'Specification-Title'   : 'moonlightcore',
                'Specification-Vendor'  : 'Leoxian',
                'Specification-Version' : project.jar.archiveVersion,
                'Implementation-Title'  : 'moonlightcore',
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor' : 'Leoxian',
                'Built-On-Minecraft'    : mcVersion
        ])
    }
}

processResources {
    var expandedProps = [
            'version': modVersion, 'minecraftVersion': mcVersion, 'minecraftVersionRange': mcVersionRange,
            'forgeVersion': forgeVersion, 'forgeVersionRange': forgeVersionRange, 'fmlVersionRange': fmlVersionRange,
            'fabricApiVersion': fabricApiVersion, 'fabricLoaderVersion': fabricLoaderVersion
    ]

    var jsonExpandedProps = expandedProps.collectEntries {
        key, value -> [(key): value instanceof String ? value.replace("\n", "\\\\n") : value]
    }

    filesMatching(['META-INF/mods.toml']) {
        expand expandedProps
    }

    filesMatching(['pack.mcmeta', 'fabric.mod.json', '*.mixins.json']) {
        expand jsonExpandedProps
    }

    inputs.properties(expandedProps)
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId base.archivesName.get()
            artifact(tasks.jar)
            artifact(tasks.sourcesJar)
        }
    }
    repositories {
        maven {
            url = "file://" + System.getenv("maven_local")
        }
    }
}