plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'com.diffplug.spotless'
}

project.group = "${modGroup}"
project.version = "${modVersion}"

if(!modVersionType.equalsIgnoreCase("stable")) {
    project.version += "-${modVersionType}"
}

base {
    archivesName = "moonlightcore-${project.name.toLowerCase(Locale.ROOT)}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(modJavaVersion)
    withSourcesJar()
    withJavadocJar()
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Sponge"
                url = "https://repo.spongepowered.org/repository/maven-public/"
            }
        }
        filter {
            includeGroupByRegex('org.spongepowered')
        }
    }
    exclusiveContent {
        forRepositories(
                maven {
                    name = "Parchment"
                    url = "https://maven.parchmentmc.org/"
                },
                maven {
                    name = "NeoForge"
                    url = "https://maven.neoforged.net/releases"
                }
        )
        filter {
            includeGroup('org.parchmentmc.data')
        }
    }

    mavenCentral()
}

['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations."$variant".outgoing {
        capability("de.leoxian.moonlightcore:${project.name}:$version")
        capability("de.leoxian.moonlightcore:${base.archivesName.get()}:$version")
        capability("de.leoxian.moonlightcore:moonlightcore-${project.name}-${mcVersion}:$version")
        capability("de.leoxian.moonlightcore:moonlightcore:$version")
    }

    publishing.publications.configureEach {
        suppressPomMetadataWarningsFor(variant)
    }
}

sourcesJar {
    from(rootProject.file("LICENSE")) {
        rename { "${it}_MoonlightCore"}
    }

    archiveClassifier = "sources"
}

spotless {
    java {
        removeUnusedImports()
        formatAnnotations()
    }
}

tasks.withType(Jar).configureEach {
    from (rootProject.file("LICENSE")) {
        rename { "${it}_MoonlightCore"}
    }

    manifest.attributes([
            "Specification-Title": "MoonlightCore",
            "Specification-Vendor": "Leoxian",
            "Specification-Version": "1",
            "Implementation-Title": "moonlightcore",
            "Implementation-Vendor": "Leoxian",
            "Implementation-Version": "${modVersion}-${modVersionType}",
            "Built-On-Minecraft": "${mcVersion}"
    ])
}

tasks.withType(ProcessResources).configureEach {
    def extendedProps = [
            modVersion: project.version,
            mcVersion: mcVersion, mcVersionRange: mcVersionRange,
            forgeVersion: forgeVersion, forgeVersionRange: forgeVersionRange, fmlVersionRange: fmlVersionRange,
            fabricApiVersion: fabricApiVersion, fabricLoaderVersion: fabricLoaderVersion,
            githubUrl: githubUrl
    ]
    def jsonExtendedProps = extendedProps.collectEntries {
        key, value -> [(key): value.replace("\n", "\\\\n")]
    }

    filesMatching(["pack.mcmeta", "fabric.mod.json", "*.mixins.json"]) {
        expand(jsonExtendedProps)
    }

    filesMatching(["META-INF/mods.toml"]) {
        expand(extendedProps)
    }

    inputs.properties(extendedProps)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.withType(AbstractArchiveTask).configureEach {
    setPreserveFileTimestamps(false)
    setReproducibleFileOrder(true)
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.add("-Xlint:unchecked")
    options.encoding = "UTF-8"
    options.release = JavaLanguageVersion.of(modJavaVersion).asInt()
    options.deprecation = true
}

tasks.withType(Javadoc).configureEach {
    def stdJavadocDocletOptions = options as StandardJavadocDocletOptions
    stdJavadocDocletOptions.addStringOption("Xdoclint:none", "-quiet")
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}