plugins {
    id 'multiloader-common'
}

configurations {
    xplatJava {
        canBeResolved = true
    }
    xplatResources {
        canBeResolved = true
    }
}

dependencies {
    compileOnly project(":xplat")
    xplatJava project(path: ':xplat', configuration: 'xplatJava')
    xplatResources project(path: ':xplat', configuration: 'xplatResources')
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.xplatJava)
    source(configurations.xplatJava)
}

tasks.withType(ProcessResources).configureEach {
    dependsOn(configurations.xplatResources)
    from(configurations.xplatResources)
}

tasks.named('javadoc', Javadoc).configure {
    dependsOn(configurations.xplatJava)
    source(configurations.xplatJava)
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.xplatJava)
    from(configurations.xplatJava)
    dependsOn(configurations.xplatResources)
    from(configurations.xplatResources)
}

