plugins {
    id 'fabric-loom' version '1.11-SNAPSHOT' apply false
    id 'net.neoforged.moddev.legacyforge' version '2.0.105' apply false
    // TODO: De-comment when updating to 1.21.0
//    id 'net.neoforged.moddev' version '2.0.105' apply false

    id 'idea'
    id 'me.modmuss50.mod-publish-plugin' version '0.8.4'
}

ext {
    changelogFile = rootProject.file("changelog/${version}/changelog.md")

    secrets = new Properties()
    if (rootProject.file("secrets.properties").exists()) {
        rootProject.file("secrets.properties").withInputStream {is -> secrets.load(is) }
    }
}

subprojects { sub ->
    if(sub.name != "Xplat") {
        evaluationDependsOn(":Xplat")

        apply plugin: 'java-library'

        group = rootProject.group
        version = rootProject.version
        base.archivesName = "${modName}-${sub.name}"

        java.withSourcesJar()
        java.withJavadocJar()
        java.toolchain.languageVersion = JavaLanguageVersion.of(modJavaVersion)
        java.toolchain.vendor = JvmVendorSpec.ADOPTIUM

        repositories {
            exclusiveContent {
                forRepositories(
                        maven {
                            name = "ParchmentMC Maven"
                            url = "https://maven.parchmentmc.org"
                        },
                        maven {
                            name = "Neoforge Maven"
                            url = "https://maven.neoforged.net/releases"
                        }
                )
                filter {
                    includeGroupAndSubgroups("org.parchmentmc.data")
                }
            }

            exclusiveContent {
                forRepository {
                    maven {
                        name = 'SpongePowered Maven'
                        url = 'https://repo.spongepowered.org/repository/maven-public'
                    }
                }
                filter {
                    includeGroupAndSubgroups("org.spongepowered.mixin")
                }
            }
        }

        tasks.withType(ProcessResources).configureEach {
            dependsOn(project(":Xplat").tasks.named('processResources', ProcessResources))
            from(project(":Xplat").sourceSets.main.output.resourcesDir)

            var expandedProperties = [
                    modId: modId, modName: modName, modVersion: rootProject.version, modAuthor: modAuthor, modCredits: modCredits, modDescription: modDescription, modLicense: modLicense, modJavaVersion: modJavaVersion, modIssueTracker: modIssueTracker,

                    forgeVersion: forgeVersion, forgeVersionRange: forgeVersionRange, forgeLoaderVersionRange: forgeLoaderVersionRange,
                    fabricApiVersion: fabricApiVersion, fabricLoaderVersion: fabricLoaderVersion
            ]

            var jsonExpandedProperties = expandedProperties.collectEntries {
                key, value -> [(key): value instanceof String ? value.replace("\n", "\\\\n") : value]
            }

            filesMatching(["META-INF/mods.toml", "META-INF/neoforge.mods.toml"]) {
                expand expandedProperties
            }

            filesMatching(["fabric.mod.json", "*.mixins.json"]) {
                expand jsonExpandedProperties
            }

            inputs.properties expandedProperties
            duplicatesStrategy = DuplicatesStrategy.INCLUDE
        }

        tasks.named('jar', Jar) {
            dependsOn(project(":Xplat").tasks.named('processResources', ProcessResources))
            from(project(":Xplat").sourceSets.main.output.classesDirs)
            from(project(":Xplat").sourceSets.main.output.resourcesDir)

            manifest {
                attributes([
                        'Specification-Title': modId,
                        'Specification-Vendor': modAuthor,
                        'Specification-Version': project.version,

                        'Implementation-Title': project.name,
                        'Implementation-Vendor': modAuthor,
                        'Implementation-Version': project.jar.archiveVersion,
                        'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),

                        'Built-On-Minecraft': mcVersion
                ])
            }
        }

        tasks.withType(Javadoc).configureEach {
            def docletOptions = options as StandardJavadocDocletOptions
            docletOptions.addStringOption('Xdoclint:none', '-quiet')
        }

        tasks.withType(JavaCompile).configureEach {
            options.encoding = 'UTF-8'
            options.release = JavaLanguageVersion.of(modJavaVersion).asInt()

            source(project(":Xplat").sourceSets.main.allJava)
        }

        tasks.withType(GenerateModuleMetadata).configureEach {
            enabled = false
        }

        tasks.withType(AbstractArchiveTask).configureEach {
            setPreserveFileTimestamps(false)
            setReproducibleFileOrder(true)
        }
    }
}

// From https://modmuss50.github.io/mod-publish-plugin/multi_platform/
publishMods {
    type = "${releaseChannel}"

    if (changelogFile.exists()) {
        changelog = changelogFile.text
    }

    def cfOptions = curseforgeOptions {
        accessToken = secrets.curseforgeToken
        projectId = "${curseforgeProjectId}"

        minecraftVersions = ["${mcVersion}"]
        javaVersions = [JavaVersion.toVersion(modJavaVersion)]

        clientRequired = true
        serverRequired = true
    }

    def mrOptions = modrinthOptions {
        accessToken = secrets.modrinthToken
        projectId = "${modrinthProjectId}"
        minecraftVersions = ["${mcVersion}"]
    }

    curseforge("MlCoreForge_Curseforge") {
        from cfOptions
        file project(":Forge")

        modLoaders = ["forge"]
    }

    curseforge ("MlCoreFabric_Curseforge") {
        from cfOptions
        file project(":Fabric")

        modLoaders = ["fabric"]

        requires {
            slug = "fabric-api"
        }
    }

    modrinth("MlCoreForge_Modrinth") {
        from mrOptions
        file project(":Forge")

        modLoaders = ["forge"]
    }

    modrinth("MlCoreFabric_Modrinth") {
        from mrOptions
        file project(":Fabric")

        modLoaders = ["fabric"]
        requires {
            slug = "fabric-api"
        }
    }
}

idea.module {
    for(var excludeDirName in ["run", "out", "logs", "runs"]) {
        File excludeDir = new File(projectDir, excludeDirName)
        excludeDirs.add excludeDir
    }

    downloadSources = true
    inheritOutputDirs = false
}