org.gradle.jvmargs=-Xmx4G

group=de.leoxian.moonlightcore
modVersion=5.0.5

# Common

mcVersion=1.20.1
mcVersionRange=[1.20.1,)
parchmentVersion=2023.09.03

# Fabric

fabricApiVersion=0.92.1
fabricLoaderVersion=0.16.9

# Forge

forgeVersion=47.4.9
forgeVersionRange=[47,)
fmlVersionRange=[47,)

# Dependencies

mixinVersion=0.8.5
mixinextrasVersion=0.3.5