org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.configureondemand=false
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.configuration-cache.problems=warn
# Moonlight Core properties

modName=MoonlightCore
modId=moonlightcore
modVersion=5.0.3
modGroup=de.leoxian.moonlightcore
modDescription=Moonlight Core is an abstraction layer for multiplatform mods
modIssueTracker=https://www.github.com/leoxianx/MoonlightCore
modLicense=Custom - LICENSE.md in JAR
modAuthor=Leoxian
modCredits=Leoxian
modJavaVersion=17

# Minecraft properties

mcVersion=1.20.1
parchmentMc=1.20.1
parchmentVersion=2023.09.03

# Fabric properties

fabricApi=0.92.1
fabricLoader=0.16.9

# Forge properties

forgeVersion=47.4.9
forgeRange=[47,)
fmlRange=[47,)

# publish properties

modrinthId=6MSffsOL
curseProjectId=1152824