# Gradle Project properties

org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G
org.gradle.configuration-cache=false

group=de.leowgc.moonlightcore
version=4.0.0

# Releasing properties

modrinthProjectId=6MSffsOL
curseforgeProjectId=1152824

releaseChannel=release

# Mod properties

mcVersion=1.20.1

parchmentMc=1.20.1
parchmentVersion=2023.09.03

modJavaVersion=21

modId=moonlightcore
modName=Moonlight Core
modDescription=Moonlight Core is a layer abstraction that is aimed to give mod developers utilities for their multi-loader mods.
modIssueTracker=https://www.github.com/leoxianx/MoonlightCore
modLicense=MIT
modAuthor=LeoWgc
modCredits=LeoWgc

# Fabric properties

fabricApiVersion=0.92.1
fabricLoaderVersion=0.16.9

# MinecraftForge Properties

forgeVersion=47.2.30
forgeVersionRange=[47,)
forgeLoaderVersionRange=[0,)

