plugins {
    id 'moonlightcore-loader'
    id 'net.neoforged.moddev.legacyforge'
}

dependencies {
    compileOnly(project(":Xplat"))

    compileOnly("io.github.llamalad7:mixinextras-common:${mixinextrasVersion}")
    jarJar(runtimeOnly("io.github.llamalad7:mixinextras-forge:${mixinextrasVersion}"))
    if(System.getProperty("idea.sync.active") != "true") {
        annotationProcessor("org.spongepowered:mixin:${mixinVersion}:processor")
    }
    annotationProcessor("io.github.llamalad7:mixinextras-common:${mixinextrasVersion}")
}

import org.slf4j.event.Level
legacyForge {
    version = "${mcVersion}-${forgeVersion}"

    validateAccessTransformers = true
    accessTransformers.from project(":Xplat").file("src/main/resources/META-INF/accesstransformer.cfg")

    mods {
        create("moonlightcore") {
            sourceSet sourceSets.main
        }
    }

    parchment {
        minecraftVersion = "${mcVersion}"
        mappingsVersion = "${parchmentVersion}"
    }

    runs {
        client {
            client()

            ideName = "Forge Client"
            gameDirectory = file("run/client")
            logLevel = Level.DEBUG
        }
        server {
            server()

            ideName = "Forge Server"
            gameDirectory = file("run/server")
            logLevel = Level.DEBUG
        }
    }
}

mixin {
    add sourceSets.main, "moonlightcore.refmap.json"
    config "moonlightcore.mixins.json"
    config "moonlightcore.forge.mixins.json"
}

publishing {
    publications {
        register("forgeJar", MavenPublication) {
            artifactId = base.archivesName.get()
            artifact(tasks.jar)
            artifact(tasks.sourcesJar)
        }
    }
    repositories {
        maven {
            url = "file://" + System.getenv("maven_local")
        }
    }
}

tasks.withType(Jar).configureEach {
    manifest.attributes([
      "MixinConfigs": "moonlightcore.mixins.json,moonlightcore.forge.mixins.json"
    ])
}